spring.application.name=rideservice

server.port = 8088

spring.datasource.url = jdbc:mySql://localhost:3306/rideBooking
spring.datasource.username = root
spring.datasource.password = maneesh_1227
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true