spring.application.name=API-GATEWAY
server.port=8088
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=*

# CORS Configuration
spring.webflux.cors.allowed-origins=*
spring.webflux.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.webflux.cors.allowed-headers=*
spring.webflux.cors.allow-credentials=true

# Swagger UI configuration
springdoc.api-docs.path=/api/gateway/v3/api-docs
springdoc.swagger-ui.path=/api/gateway/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging Configuration
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.apigateway=DEBUG

# Custom Routes Configuration

# Location Service Routes
spring.cloud.gateway.server.webmvc.routes[0].id=locationservice
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/locations/**

