spring.application.name=userservice

spring.datasource.url = jdbc:mysql://localhost:3306/cab_booking
spring.datasource.username = root
spring.datasource.password = SKtagore5004
spring.jpa.hibernate.ddl-auto = update