spring.application.name=authservice
server.port = 8082

spring.datasource.url = jdbc:mySql://localhost:3306/cabBooking
spring.datasource.username = root
spring.datasource.password = maneesh_1227

spring.jpa.show-sql=true

//cabbookingsecrete
app.jwt-secrete = 705819a89f19aa889354a7b526fb5bedd143beec344fccc73aafd1fdfb0b8b47
app-jwt-expiration-milliseconds = 604800000